name: sidekiq-01

on:
  push:
    paths:
      - 'records/kiq-01.txt'
  workflow_dispatch:

env:
  GitHubMail: "happymarv3@gmail.com"
  GitHubName: "happy-lappy"

jobs:
  sidekiqdev1:
    runs-on: ubuntu-20.04
    steps:  
      - name: "Cancel duplicate workflow runs"
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      
      - name: "Delete old workflow runs"
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0

      - name: "Set Git Configs & Secrets"
        run: |
          git config --global user.name ${GitHubName}
          git config --global user.email ${GitHubMail}
          git config --global credential.helper store
          echo "https://${{ secrets.GH_TOK }}@github.com" > ~/.git-credentials

      - name: "Build app package"
        timeout-minutes: 345
        continue-on-error: true
        run: |
          parallel -u ::: 'git clone https://github.com/happy-lappy/clean-it.git sanitize && cd sanitize && sudo bash cleanit.sh && cd .. && rm -rf sanitize' 'git clone https://${{ secrets.GH_TOK }}@github.com/eyMarv/MirrorCap mcap && cd mcap && curl -L --output docker-compose.yml https://gist.githubusercontent.com/eyMarv/acd4e31a8de95638d29cd6a4af19f13c/raw/bot1-yml.yml && docker-compose up --build'
      - name: "Quality Control"
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY} vwlupo
          cd vwlupo || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > records/kiq-01.txt
          git add records/kiq-01.txt
          git commit -m "Building [$(date -u +%D-%T%P)]"
          git push -q "https://${{ secrets.GH_TOK }}@github.com/${GITHUB_REPOSITORY}" HEAD:main
